Repository VinylMusicPlayer/VinylMusicPlayer, pull requests merged in 2023-03, with the labels that each got.

#703 Use MarkdownViewDialog to improve visualising LastFM artist bio and album wiki
  app/build.gradle
  app/src/main/java/com/poupa/vinylmusicplayer/dialogs/ChangelogDialog.java
  app/src/main/java/com/poupa/vinylmusicplayer/dialogs/MarkdownViewDialog.java
  app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AboutActivity.java
  app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java
  app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/ArtistDetailActivity.java
  app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/MainActivity.java
  app/src/main/res/layout/dialog_markdown_view.xml
Labels: enhancement

#715 Enqueue song action can now be choosen in preference
  app/src/main/java/com/poupa/vinylmusicplayer/dialogs/BottomSheetDialog/BottomSheetDialogWithButtons.java
  app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java
  app/src/main/java/com/poupa/vinylmusicplayer/preferences/SongConfirmationPreference.java
  app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/SettingsActivity.java
  app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref_now_playing_screen.xml
Labels: feature request

#706 Fix snackbar unreadable text
  app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/PlayingQueueAdapter.java
  app/src/main/java/com/poupa/vinylmusicplayer/discog/SnackbarUtil.java
  app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java
  app/src/main/res/values/styles.xml
  app/src/main/res/values/styles_parents.xml
Labels: bug

#728 Avoid crash while loading top tracks
  app/src/main/java/com/poupa/vinylmusicplayer/loader/TopAndRecentlyPlayedTracksLoader.java
Labels: bug

#726 Cab icon tint
  app/src/main/java/com/poupa/vinylmusicplayer/dialogs/BottomSheetDialog/BottomSheetDialog.java
  app/src/main/java/com/poupa/vinylmusicplayer/dialogs/BottomSheetDialog/BottomSheetDialogWithButtons.java
Labels: bug
